#!/bin/bash

u=`id -u`
if [ "$u" == 0 ]; then
	p=/
else
	p=~/
fi

while :
do
	d=`date '+%Y.%m.%d %H:%M:%S'`

	g=`cat /sys/devices/virtual/thermal/thermal_zone0/temp`
	g=" | GPU : "`echo "$g" | rev | cut -b 4- | rev`\'C

	c=""
	if [ "$u" == 0 ]; then
		c=`vcgencmd measure_temp`
		c=" | CPU : ${c#*=}"
	fi

	o="$d$g$c"



	echo "$o" | tee -a ${p}temp.out

	sleep 3
done
